### ISSUE TITLE
Support for Existing Definitions and Signatures

### ISSUE THREAD

**Issue by seglberg** [vmagamedov/grpclib#20]
I am very excited about a project like this finally making progress on proper concurrency support for grpc. 

I am curious about the vision for this library. I understand that grpcio is not a run time requirement, but since the standard grpcio library is already in wide use, I think it would be beneficial to create "shim" library instead of a replacement.

For example, consider using the grpc definitions generated by the upstream protobuf compiler and using the existing workflow and method signatures. This is made possible since a subclass can override a parent's method with an async version.

For example:
```python
# Standard gRPC

import futures
import grpc
import example_pb2
import example_pb2_grpc

class ExampleServicer(example_pb2_grpc.ExampleServicer):
    def GetSomething(request, context):
         value = do_something(request.param)
         return example_pb2.Something(value=value)

    def GetSomething2(request, context):
         value = do_something2(request.param)
         return example_pb2.Something2(value=value)

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    example_pb2_grpc.add_ExampleServicer_to_server(ExampleServicer(), server)
    server.add_insecure_port('[::]:50051')
    server.start()
```
```python
# Shimmed gRPC

import asyncio
import grpclib
import example_pb2
import example_pb2_grpc

class ExampleServicer(example_pb2_grpc.ExampleServicer):
    async def GetSomething(request, context):
        # Notice this method has become async
        # and should be called as a coroutine.
        value = await do_something_async(request.param)
        return example_pb2.Something(value=value)

    def GetSomething2(request, context):
         # Notice this method is not async
         # and should be called as a normal method.
         # Perhaps run_in_executor?
         value = do_something2(request.param)
         return example_pb2.Something2(value=value)

def serve():
    loop = asyncio.get_event_loop()
    server = grpclib.server(loop)
    example_pb2_grpc.add_ExampleServicer_to_server(ExampleServicer(), server)
    server.add_insecure_port('[::]:50051')
    server.start()  # loop.run_forever() ?
```

I think this would massively increase the adoption rate of this library. We have a few hundred definitions at the moment and essentially rewriting the servicers would be difficult at this point. Being able to move over different rpc methods to async as we touch them would be amazing. Personally I could care less that the grpcio requirement is removed, since we are already using it at this point.

Another idea would be to make the behavior of grpclib match that of the orginal grpcio library. For example, we rely on exceptions being propagated in order to capture them by Sentry but grpclib behavior is to swallow exception. This means we would have to rely on some monkey patching to hook capturing of exceptions at this point.

Again, awesome work on this! I am just curious to see what other think about adopting a library like this in their projects.

:+1: :sunglasses:

**Comment by vmagamedov** [comment]
Hi, thanks for a good questions!

I wasn't thinking about smooth migration paths from grpcio to grpclib, because synchronous and asynchronous ecosystems are almost completely different: db drivers, requests/aiohttp and so on. And this means that you have to rewrite project in order to make a switch. But:

> Being able to move over different rpc methods to async as we touch them would be amazing

– this sounds great to me, however, I had some reasons not to copy Google's APIs as is.

Take a look at what grpcio generates:
```python
import grpc
~~~~~~~~~~~

def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          servicer.SayHello,
          request_deserializer=helloworld_dot_helloworld__pb2.HelloRequest.FromString,
          response_serializer=helloworld_dot_helloworld__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      'helloworld.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
```
First of all, it is not possible just to use this code without monkey-patching. So we still need to generate our own stubs.

Googlers are trying to implement consistent APIs and behaviour among different languages. This helps, especially when you don't have great documentation for every language. But for Python users I think this looks very unconvincing. gRPC is awesome protocol, but this awesomeness is hidden somewhere. As for myself, I've gotten interested into this protocol only after watching a talk from JavaDay conference, and this was just a coincidence.

That's why I think that it is better to have great documentation and own pythonic APIs. I'm not sure that I currently have a greatest API possible, but I'm sure that grpcio currently distracts lots of potential users and they continue to use familiar and approachable to them REST/Swagger, JSON-RPC or something else, because grpcio is a complex and heavy project with poor documentation and weird API.

I think that it is possible to implement some "shim" library on top of grpclib, which will make possible to use sync and async modes at the same time for migration purposes, with compatible to grpcio API, but I don't want to implement this in grpclib.

P.S. About this:
> we rely on exceptions being propagated in order to capture them by Sentry but grpclib behavior is to swallow exception

Can you submit an issue about this? I need more details about what you're expecting and what's wrong with grpclib, and how you're tracking exceptions using Sentry in grpcio. Is this somehow related to a some kind of interceptors support in grpclib?
