### ISSUE TITLE
False-positive isinstance assert after generation

### ISSUE THREAD

**Issue by condemil** [vmagamedov/grpclib#26]
Python version: 3.6.5
OS: macOS 10.13.5
Tested versions: 0.1.0 and 0.1.1rc2

The following [line](https://github.com/vmagamedov/grpclib/blob/master/grpclib/encoding/proto.py#L8) gives false-positive AssertionError for generated class. When I removed the assert I was able to call the server and received the proper response.

How to reproduce:
To reproduce the issue the `helloworld_pb2.py` and `helloworld_grpc.py` files from hello world example should be re-generated with `grpc_tools` command inside the current directory.

- Go to directory `grpclib/example/helloworld/`
- Run the command

      python3 -m grpc_tools.protoc -I. --python_out=. --python_grpc_out=. helloworld.proto

be aware that the command called from the same directory where `.proto` file is located

- Run `server.py`
- Call server with command

      grpcurl -plaintext -proto helloworld.proto 127.0.0.1:50051 helloworld.Greeter/UnaryUnaryGreeting

This issue prevents you to store `.proto` files aside `.py` sources.

**Comment by vmagamedov** [comment]
Sorry, I was unable to reproduce this AssertionError.

When you generate files inside `example/helloworld` directory with a following command:
```
python3 -m grpc_tools.protoc -I. --python_out=. --python_grpc_out=. helloworld.proto
```
you are getting modules with broken imports:
```diff
# in file example/helloworld/helloworld_grpc.py
-import helloworld.helloworld_pb2
+import helloworld_pb2
```
And when I start the server, I'm getting this error:
```pytb
~/ws/grpclib/example$ python3 -m helloworld.server
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/vm/ws/grpclib/example/helloworld/server.py", line 5, in <module>
    from .helloworld_grpc import GreeterBase
  File "/Users/vm/ws/grpclib/example/helloworld/helloworld_grpc.py", line 9, in <module>
    import helloworld_pb2
ModuleNotFoundError: No module named 'helloworld_pb2'
```
I can imagine only one case, when you can get such AssertionError: you probably generated and imported two versions of the same helloworld_pb2.py module from different locations, so you have equal but not the same classes and isinstance check fails.

> store .proto files aside .py sources

– what do you mean? It is possible to store .proto files aside .py sources, as long as you're not braking import system of protoc compiler and generated python modules. It is so easy to mess with protoc options :)

**Comment by condemil** [comment]
Sorry I forgot to mention that I install helloworld with `pip install -e .` and the following `setup.py`:

    from setuptools import setup, find_packages

    setup(
        name='helloworld',
        version='0.0.0',
        packages=find_packages(),
    )

and updated `server.py`:

```diff
-from .helloworld_pb2 import HelloReply
-from .helloworld_grpc import GreeterBase
+from helloworld.helloworld_pb2 import HelloReply
+from helloworld.helloworld_grpc import GreeterBase
```

This way you will not get the `ModuleNotFoundError`.

> It is possible to store .proto files aside .py sources, as long as you're not braking import system of protoc compiler and generated python modules. It is so easy to mess with protoc options :)

I tried to generate python modules with different combination of parameters and always end up with broken imports, for example I moved `helloworld/helloworld.proto` to `protos/hellowold.proto` and tried the following command

```
https://grpc.io/docs/tutorials/basic/python.html#generating-client-and-server-code
```
After that imports was broken the same way as you specified above. Probably you know a solution to generate modules with proper imports when your proto files located aside?

**Comment by vmagamedov** [comment]
There is often a misconception about `protoc` include path, package name, .proto files structure on the file system and modules structure in a Python project. And I don't know good docs explaining all that things.

1. That package name in .proto file in Python is used only to namespace messages and services, e.g. `some.package.MessageName` or `/some.package.ServiceName/MethodName`, to avoid conflicts with names. Nothing else.

2. `protoc` assumes, that generated Python modules **must** match .proto files structure, and it generates imports between these modules accordingly. Example:
```
some
    package
        foo.proto
        bar.proto
```
And you want to import message from foo.proto in bar.proto:
```protobuf
// you inside some/package/bar.proto file
import 'some/package/foo.proto';
```
This import system somewhat similar to the import system of Python, and here is what you will get after running `protoc -I. --python_out=. some/package/*.proto`:
```
some
    package
        foo_pb2.py
        bar_pb2.py
```
As you see, files structure is the same, and imports are almost the same in the `bar_pb2.py`:
```python
from some.package import foo_pb2 as some_dot_package_dot_foo__pb2
```
3. Include path lets also find out where your package begins, so you will be able to use structure like this:
```
my-proto-files
    some
        package
            foo.proto
            bar.proto
```
And you will be able to compile them with this command:
```
$ protoc -Imy-proto-files --python_out=. my-proto-files/some/package/*.proto
           ^^^^^^^^^^^^^^                ^^^^^^^^^^^^^^
```
But this doesn't changes structure of generated files, it would be the same.

4. `--python_out` and other `--*_out` options should point to the sources root directory. It is wrong to generate files inside another package like this:
```
protoc -I my-proto-files --python_out=src/project/protos my-proto-files/some/package/*.proto
                                          ^^^^^^^
```
... where ``project`` is a root Python package of your project.

And it is wrong to assume that you will be able to get project structure like this:
```
src
    project
        __init__.py
        protos
            __init__.py
            some
                package
                    foo_pb2.py
                    ...
```
Imports will be broken. In order to have project structure like this, you should use the same structure for your .proto files. Or maybe at some point this issue will be fixed in the protoc compiler.

So, in your case, you can store .proto file as `protos/hellowold/hellowold.proto`, and generate python modules with this command:
```
$ protoc -Iprotos --python_out=. --python_grpc_out=. protos/helloworld/helloworld.proto
```

**Comment by condemil** [comment]
Thank you for such a detailed explanation. It is now clear that to store proto files aside it is required to create same directory tree structure similar to modules you created in python sources. I will close the ticket because there is nothing to fix from grpclib but I am sure your explanation will prevent further similar questions from people who struggle with modules generation from proto files.
