### ISSUE TITLE
Usage: channels

### ISSUE THREAD

**Issue by dfee** [vmagamedov/grpclib#34]
On the server side, I can have multiple handlers all served together.

On the client side, is there a penalty, or something wrong, by not sharing a channel between multiple stubs (either by stub class or stub instance)?

**Comment by vmagamedov** [comment]
It is a preferred way to use a single channel per server – to use a single multiplexed HTTP/2 connection from client to server, because HTTP/2 was designed in this way. There is no need and no benefits to use several connections. On the contrary, features like flow control will work worse with several connections.

**Comment by dfee** [comment]
Wow. Glad I asked. So then it's one `Channel` per host / port right?

**Comment by vmagamedov** [comment]
> So then it's one Channel per host / port right?

Yes.
