### ISSUE TITLE
How to add Channel Credentials?

### ISSUE THREAD

**Issue by maitham** [vmagamedov/grpclib#84]
I currently have the following code:

```
composite_credentials = grpc.composite_channel_credentials(
            ssl_credentials, google_auth_credentials
        )
Channel(host, port, ssl=composite_credentials, loop=loop)
```

This doesn't work as this returns a composite ChannelCredentials object as per https://www.grpc.io/docs/guides/auth/ . Is this currently supported? Or should I try to get the headers required for authenticating requests to google?

**Comment by vmagamedov** [comment]
grpclib currently has only basic building blocks to perform authentication. Vendor-specific auth mechanisms (Google) aren't supported because I'm not using these services and I don't know the best way to implement this functionality.

If you want to use certificate-based auth – use ssl option when create Channel:
```
Channel(..., ssl=custom_ssl_context)
```
This `ssl` option can be `True` or instance of the `ssl.SSLContext` class. So it is not possible to pass your `composite_credentials` to this option. I have an example of how to perform mutual TLS auth: [examples/mtls/client.py](https://github.com/vmagamedov/grpclib/blob/master/examples/mtls/client.py), maybe this will help. And probably I have to add more documentation about TLS authentication.

If you want to use token-based auth – make sure you're using secure connection (`Channel(..., ssl=True)`), and send auth token with request metadata. There is two ways to send auth token in request metadata:
- explicitly in every request: `stub.Method(..., metadata={token})`
- implicitly using events: https://grpclib.readthedocs.io/en/latest/events.html

Can you provide an example of how to authenticate with Google using existing functionality in grpclib I mentioned above? Maybe I can add more helpers into grpclib and/or document this properly with examples.

**Comment by maitham1** [comment]
I'm trying to use the auth token method. However even with and without a token I get the following error `(<Status.UNIMPLEMENTED: 12>, "Received :status = '404'")` .

**Comment by vmagamedov** [comment]
Turns out that Google detects gRPC protocol by reading content-type header:
- I'm getting `:status 404` when I send `content-type application/grpc+proto`
- I'm getting proper `grpc-status` when I send `content-type application/grpc`

But gRPC protocol says that both variants are valid: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

Unfortunately grpclib doesn't allow you to set your custom content-type header value.
