### ISSUE TITLE
Explain to me please someone why is happening with this?

### ISSUE THREAD

**Issue by healfy** [vmagamedov/grpclib#89]
```
from typing import Type, TYPE_CHECKING

from .base import CodecBase


if TYPE_CHECKING:
    from .._protocols import IProtoMessage  # noqa


class ProtoCodec(CodecBase):
    __content_subtype__ = 'proto'

    def encode(
        self,
        message: 'IProtoMessage',
        message_type: Type['IProtoMessage'],
    ) -> bytes:
        if not isinstance(message, message_type):
            raise TypeError('Message must be of type {!r}, not {!r}'
                            .format(message_type, type(message)))
        return message.SerializeToString()

    def decode(
        self,
        data: bytes,
        message_type: Type['IProtoMessage'],
    ) -> 'IProtoMessage':
        return message_type.FromString(data)
```

I had u huge and unobvious bug with this, 
<class 'observer_pb2.CheckBalanceResponse'> -- is result if type(message)
<class 'observer_pb2.CheckBalanceResponse'> -- message_type
And isinstance says that is False.
Because I imported my message CheckBalanceResponse directly from the file
`from rpc import observer_pb2`
And it doesn't work, but when I changed import to
`from rpc.observer_pb2_grpc import observer__pb2` everything has worked,
in observer_pb2_grpc 
`import observer_pb2 as observer__pb2`
But in fact these are two identical message classes,
Why not just do a type check?

**Comment by vmagamedov** [comment]
You're probably generated same messages twice (same `.proto` file, two copies of `*_pb2.py` files), so you have two ways to import them.

Try to delete all existing `*_pb2.py` files and regenerate them more carefully. There is a common misunderstanding on how to use `-I` and `--*_out=` options:
- `--*_out=` option should point to the directory, where your **top-level** python package is located, e.g. `.` - when your top-level package is located in the root of your repository
- `-I` option should point to the directory, where your **top-level** proto package is located, e.g. `.` - when your proto files are located within python source files in the root of your repository

Our examples should be suitable to you: https://github.com/vmagamedov/grpclib/tree/master/examples

I can't rely on type checking here because type checking is optional. And this can lead to bugs in your codebase, where you may also rely on `isinstance`. So proper code generation is a must.
